CREATE TABLE IF NOT EXISTS media_objects (id TEXT PRIMARY KEY,type TEXT NOT NULL,parts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS media_chunks (file_id TEXT NOT NULL,part INTEGER NOT NULL,bytes BLOB NOT NULL,PRIMARY KEY(file_id,part));
