import React from 'react';
import { marked } from 'marked';
import sanitize from 'sanitize-html';
import { SiteData, Article, categories } from './model';

export function markdown(body:string){return sanitize(marked.parse(body,{async:false}) as string,{allowedTags:sanitize.defaults.allowedTags.concat(['img','h1','h2','h3','h4','h5','h6']),allowedAttributes:{...sanitize.defaults.allowedAttributes,img:['src','alt','width','height'],a:['href','title'],th:['align'],td:['align']},allowedSchemes:['https','mailto'],allowProtocolRelative:false});}
export function prettyDate(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('tr-TR',{year:'numeric',month:'long',day:'numeric',timeZone:'UTC'});}
const Arrow=()=> <span aria-hidden="true">↗</span>;
export function ArticleRows({items}:{items:Article[]}){return <div className="article-list">{items.map(a=><a className="article-row" href={'/makale/'+a.slug+'.html'} key={a.slug}><div className="article-meta"><span>{categories[a.category]}</span><span>{prettyDate(a.date)}</span></div><div><h3>{a.title}</h3><p>{a.summary}</p><div className="tags">{a.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div></div><Arrow/></a>)}</div>}
export function Site({data,page='home',slug='',preview=false}:{data:SiteData;page?:string;slug?:string;preview?:boolean}){
 const {profile:p,theme}=data;const articles=data.articles.filter(a=>a.published).sort((a,b)=>b.date.localeCompare(a.date));
 const article=data.articles.find(a=>a.slug===slug);const project=data.projects.find(x=>x.slug===slug);
 const projects=()=> <div className="project-grid">{data.projects.map((x,i)=><a href={'/projeler/'+x.slug+'.html'} className={'project-card project-'+i%2} key={x.slug}><div className="project-top"><span className="project-number">0{i+1} / PROJE</span><Arrow/></div>{x.image?<img src={x.image} alt={x.title}/>:<div className="project-monogram" aria-hidden="true">{x.title.split(' ').map(s=>s[0]).join('').slice(0,2)}</div>}<span className="eyebrow">{x.status}</span><h3>{x.title}</h3><p>{x.summary}</p><span className="text-link">Projeyi incele <Arrow/></span></a>)}</div>;
 const section=(b:SiteData['blocks'][number])=>{
  if(!b.visible)return null;
  if(b.type==='hero')return <section className="hero" key={b.id}><div className="hero-main"><span className="eyebrow"><i/> Siyaset bilimi · Kamu yönetimi · Teknoloji</span><h1>{b.title}</h1><p className="hero-intro">{b.body||p.intro}</p><div className="hero-links"><a className="button" href="/calisma-metinleri.html">Araştırmaları keşfet <Arrow/></a><a className="text-link" href="/projeler.html">Üzerinde çalıştıklarım <Arrow/></a></div></div><aside className="hero-note"><span className="eyebrow">ARAŞTIRMA NOTU / 01</span><p>Teknoloji değişirken, <br/><em>kamusal sorumluluk</em> <br/>nerede duruyor?</p><div className="note-rule"/><span>Güven, şeffaflık ve hesap verebilirlik üzerine.</span><a href="/ozgecmis.html">Araştırma perspektifim <Arrow/></a></aside><div className="hero-bottom"><span>Talha Nuri Yılmaz</span><span>{p.role}</span></div></section>;
  return <section key={b.id} className={'section block-'+b.type+' columns-'+b.columns}><div className="section-heading"><div><span className="eyebrow">{({research:'ARAŞTIRMA',projects:'TASARIMDAN UYGULAMAYA',writing:'DÜŞÜNCE DEFTERİ',text:'NOTLAR',image:'GÖRSEL',timeline:'DENEYİM',contact:'İLETİŞİM'} as Record<string,string>)[b.type]}</span><h2>{b.title}</h2></div>{b.type==='research'?<a className="text-link" href="/calisma-metinleri.html">Tüm çalışmalar <Arrow/></a>:b.type==='writing'?<a className="text-link" href="/denemeler.html">Tüm yazılar <Arrow/></a>:null}</div>{b.type==='research'?<ArticleRows items={articles.filter(a=>a.category==='research').slice(0,3)}/>:b.type==='writing'?<ArticleRows items={articles.filter(a=>a.category!=='research').slice(0,3)}/>:b.type==='projects'?projects():b.type==='contact'?<div className="contact-block"><p>{b.body||'Araştırma, teknoloji ve ortak projeler üzerine konuşmak için.'}</p><a href={'mailto:'+p.email}>{p.email} <Arrow/></a></div>:b.type==='image'?b.image?<figure><img className="wide-image" src={b.image} alt={b.title}/><figcaption>{b.body}</figcaption></figure>:null:<div className="prose" dangerouslySetInnerHTML={{__html:markdown(b.body)}}/>}</section>;
 };
 return <div className={`site palette-${theme.palette} typography-${theme.typography} density-${theme.density}`}>
 <a href="#main" className="skip-link">İçeriğe geç</a><header className="site-header"><a href="/" className="brand"><span className="brand-mark">tny<span>.</span></span><span>Talha Nuri Yılmaz<small>Araştırmacı & ürün geliştirici</small></span></a><nav aria-label="Ana gezinme">{[['/','Ana sayfa','home'],['/calisma-metinleri.html','Araştırmalar','research'],['/denemeler.html','Yazılar','writing'],['/projeler.html','Projeler','projects'],['/ozgecmis.html','Hakkımda','about']].map(([href,label,id])=><a href={href} key={id} aria-current={page===id?'page':undefined}>{label}</a>)}</nav><a className="header-contact" href={'mailto:'+p.email}>İletişim <Arrow/></a><details className="mobile-menu"><summary>Menü <span>☰</span></summary><nav aria-label="Mobil gezinme"><a href="/">Ana sayfa</a><a href="/calisma-metinleri.html">Araştırmalar</a><a href="/denemeler.html">Yazılar</a><a href="/projeler.html">Projeler</a><a href="/ozgecmis.html">Hakkımda</a><a href={'mailto:'+p.email}>İletişim</a></nav></details></header>
 <main id="main">{page==='home'?data.blocks.map(section):page==='research'||page==='writing'?<section className="section archive"><span className="eyebrow">{page==='research'?'ARAŞTIRMA ARŞİVİ':'DÜŞÜNCE DEFTERİ'}</span><h1>{page==='research'?'Kamuyu, teknolojiyi ve dönüşümü anlamak.':'Sorular, denemeler, düşünceler.'}</h1><p className="lead">{page==='research'?'Kamu yönetimi ve dijital dönüşüm üzerine çalışma metinleri.':'Siyaset, toplum ve teknoloji üzerine yazılar.'}</p><ArticleRows items={articles.filter(a=>page==='research'?a.category==='research':a.category!=='research')}/></section>:page==='projects'?<section className="section archive"><span className="eyebrow">PROJELER</span><h1>Fikirden çalışan ürüne.</h1><p className="lead">Araştırma merakını gündelik ihtiyaçlarla buluşturan dijital çalışmalar.</p>{projects()}</section>:page==='about'?<section className="section about"><span className="eyebrow">HAKKIMDA</span><h1>{p.name}</h1><p className="lead">{p.role}</p><div className="about-grid"><div className="prose" dangerouslySetInnerHTML={{__html:markdown(p.bio)}}/><aside className="about-note"><span className="eyebrow">DOKTORA ARAŞTIRMASI</span><h3>{p.thesis}</h3><p>Osmaniye Korkut Ata Üniversitesi<br/>Siyaset Bilimi ve Kamu Yönetimi</p>{p.orcid&&<a href={p.orcid}>ORCID kaydı <Arrow/></a>}</aside></div></section>:page==='article'&&article?<article className="reader"><a className="back" href={article.category==='research'?'/calisma-metinleri.html':'/denemeler.html'}>← Yazılara dön</a><div className="article-meta"><span>{categories[article.category]}</span><span>{prettyDate(article.date)}</span><span>{Math.max(1,Math.ceil(article.body.split(/\s+/).length/220))} dk okuma</span></div><h1>{article.title}</h1><p className="reader-author">{p.name}</p><div className="reader-actions">{!preview&&<a className="button" href={'/assets/pdf/'+article.slug+'.pdf'}>PDF indir ↓</a>}{!preview&&<a className="text-link" href={'/assets/citations/'+article.slug+'.bib'} download>Atıf kaydı (.bib) ↓</a>}</div><div className="prose" dangerouslySetInnerHTML={{__html:markdown(article.body)}}/></article>:page==='project'&&project?<section className="section about"><a className="back" href="/projeler.html">← Projelere dön</a><span className="eyebrow">{project.status}</span><h1>{project.title}</h1><p className="lead">{project.summary}</p>{project.image&&<img className="wide-image" src={project.image} alt={project.title}/>}<div className="prose" dangerouslySetInnerHTML={{__html:markdown(project.body)}}/>{project.url&&<a className="button" href={project.url}>Projeyi ziyaret et <Arrow/></a>}</section>:<section className="section archive"><span className="eyebrow">404</span><h1>Bu sayfa bulunamadı.</h1><a className="button" href="/">Ana sayfaya dön →</a></section>}</main>
 <footer className="site-footer"><div><a className="brand-name" href="/">Talha Nuri Yılmaz<span>.</span></a><p>Kamu, teknoloji ve toplum üzerine.</p></div><div className="footer-links">{p.github&&<a href={p.github}>GitHub <Arrow/></a>}{p.linkedin&&<a href={p.linkedin}>LinkedIn <Arrow/></a>}{p.orcid&&<a href={p.orcid}>ORCID <Arrow/></a>}<a href={'mailto:'+p.email}>E-posta <Arrow/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Talha Nuri Yılmaz</span><span>Merakla araştır, özenle üret.</span></div></footer></div>;
}
